(deftheme fermionqs
  "Created 2024-07-12.")

(custom-theme-set-faces
 'fermionqs
 '(default ((t (:family "Zed Mono" :foundry "UKWN" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#bdbdb3" :background "#2a2a2a" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#BDBDBD" :background "#ffdd33"))))
 '(fixed-pitch ((t (:family "Zed Mono" :foundry "UKWN" :width normal :height 120 :weight normal :slant normal))))
 '(variable-pitch ((t (:family "Zed Mono" :foundry "UKWN" :width normal :height 120 :weight normal :slant normal))))
 '(escape-glyph ((t (:foreground "#e0e0e0"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#fffe0a"))))
 '(highlight ((t (:background "#333333"))))
 '(region ((t (:extend t :background "#555555"))))
 '(shadow ((t (:foreground "#858585"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((t (:weight bold :background "white"))))
 '(font-lock-builtin-face ((t (:foreground "#f3e700"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#4e4e4e"))))
 '(font-lock-comment-face ((t (:foreground "#5e5e5e"))))
 '(font-lock-constant-face ((t (:foreground "#9189a4"))))
 '(font-lock-doc-face ((t (:foreground "#7d7c61"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#ffdd33"))))
 '(font-lock-keyword-face ((t (:foreground "#7d8991"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#dF9522"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#58724e"))))
 '(font-lock-type-face ((t (:foreground "#cd5542"))))
 '(font-lock-variable-name-face ((t (:foreground "#f6c06a"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "red"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#68a5e9"))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#68a5e9"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:background "#1f1f1f"))))
 '(header-line ((t (:foreground "gray13" :background "#bdbdb3"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#d3d3d3" :background "#333333"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width (2 . 2) :color "#454444" :style released-button)))))
 '(mode-line-inactive ((t (:foreground "#6b695c" :background "#232323"))))
 '(isearch ((t (:foreground "gray13" :background "#5180b3"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "#ab75c3" :background "#444444"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "khaki1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'fermionqs)
